#!/usr/bin/python
###############################################################
## myGpsPipe
## Author: Todd Sukolsky
## Copyright of Todd Sukolsky and Re.Cycle
## Date Created: 2/9/2013
## Last Revised: 4/8/2013
###############################################################
## Description:
##    This module is responisble for piping the raw NMEA strings
## from the GPS to a file in the system that other things can 
## utilize.
##
###############################################################
## Changes to be made:
##	Which files are actually being wrriten to and such
###############################################################
## Revisions:
##	Changed which device is used by default.
###############################################################

import time
import os
import serial
import sys
import optparse

##OPTPARSER INFO
use = "Usage: %prog [options] <arguments>"
parser = optparse.OptionParser(usage=use)
parser.add_option('-b', '--baud', dest='baud', help='Set baud rate', type=int)
parser.add_option('-D', '--device', dest='device',help='Serial Port', type=str)
parser.add_option('-d', '--debug', dest='debug',help='Debug Option')

(options, args) = parser.parse_args()

if options.device is None:
  	options.device='/dev/ttyO2'
if options.baud is None:
    	options.baud=int(9600)
if options.debug is None:
	options.debug=False

###########################################################################################
#########################   	Method for placing Time 	###########################
###########################################################################################
def placeTime(timeString):
	#WRITEFILE='/home/todd/Documents/GitHubProjects/beagle-bone.git/NMEA/initTime.txt'
	WRITEFILE='/home/root/Documents/tmp/nmea/savedTimeFile.txt'
	
	#Parse the time, then alert the sendTime script that it needs to execute.
	try:
		logFile=open(WRITEFILE,'a')	#append as a log
	except:
		exit()
		
	#Split the string
	fields=timeString.split(',')
	if (timeString.find('GPRMC') != -1) and (fields[2] == 'A'):	#found it, valid, save latest data
		time=fields[1]
		date=fields[9]			
		dmy=date[2:4]+','+date[:2]+',20'+date[4:6]
		hms=str(int(time[:2])-4)+':'+time[2:4]+':'+time[4:6]		#converts from UTC to EST
		
		#Initiate program for communication with the Watchdog_AVR with the new time.
		sendString='S'+hms+'/'+dmy+'.'		
		logFile.write(sendString+'\n')
		subprocess.call("./../CommScripts/commWAVR","-s",sendString) #put the binary sendTime in the /bin folder.
		print 'Time and date is '+sendString
		return False
 	else:
		logFile.write('NONE\n')	#don't need to initiate sending routin#wait 45 seconds before trying again.
		return True

	writefile.close()

###########################################################################################
#########################   End-Method for placing Time 	###########################
###########################################################################################



###########################################################################################
#########################   	   Main Program			###########################
###########################################################################################

#Declare where the NMEA strings are going to be written
nmeaFile='/home/root/Documents/tmp/nmea/raw_strings.txt'
#nmeaFile='/home/todd/Documents/GitHubProjects/beagle-bone.git/NMEA/raw_strings_dev.txt'
hnmeaFile=open(nmeaFile,'w')	#we are appending to this file

## Open serial connection that is going to be used for GPS
UART_PORT=str(options.device)
baud=options.baud
GPSport = serial.Serial(
        port=UART_PORT,
        baudrate=baud,
        parity=serial.PARITY_NONE,
        stopbits=serial.STOPBITS_ONE,
        bytesize=serial.EIGHTBITS
)

try:
	GPSport.open()
	if options.debug:
		print 'Port ' + UART_PORT + ' is open.'
except:
	print 'Error opening port: ' + UART_PORT
	exit()

## Serial port is open, time to start streaming
## Note: NMEA strings terminated by '\n'
currentString=''
stringsWrittenTime=0
stringsWrittenThisSection=0
noError=True
getTime=True
timeSlept=0
char=''
while noError:
	if GPSport.inWaiting() > 0:
		char=GPSport.read(1)	##read one character at a time. as long as this system runs faster than GPS, does fine
		#New if with that last read	
		if char=='\n':
			#New, valid, line- add to string then print to file
			currentString += char
			if options.debug:
				print currentString
	
			hnmeaFile.write(currentString) 			#newline is already appended on end
			stringsWrittenThisSection += 1
			#This section will check to see if string is valid for time output to AVR. If we are in a 40 second increment of the loop and the time is not set, we should send the current string to the function and wait to see if it was a valid. If it was valid the function returns False and we no longer go through this loop; if invalid returns True and we will try another few strings ONLY for this 40 second increment. If it is true, it will not go on the next 40 second increment, but only after a half hour
			if timeSlept%5==0 and getTime:	#if in first 40 seconds, look for real string
				getTime=placeTime(currentString)
				

			currentString=''				#reset string
		elif char!='\00' and char != ' ':			#no new line, just another character, add to string
			currentString+= char	
			
		if stringsWrittenThisSection >= 15:
			time.sleep(4)
			timeSlept+=1 
	                stringsWrittenThisSection=0

        if timeSlept >= 225:  #450 represents every hour
			timeSlept=0
			getTime=True		

exit()
